name: swgs-binsize
channels:
  - conda-forge
  - bioconda 
dependencies:
  - r-base=3.6.3
  - snakemake=5.10.0
  - pandas=1.1.1
  - ruamel.yaml=0.16.12
  - samtools=1.10
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - r-tidyverse=1.3.0
  - r-matrixstats=0.56.0
  - r-plyr=1.8.6
  - r-domc=1.3.6
  - r-foreach=1.5.0
  - bioconductor-qdnaseq
  - bioconductor-qdnaseq.hg19
  - r-ggridges=0.5.1
  - r-data.table=1.12.2
  - bioconductor-GenomicRanges=1.38.0
  - bioconductor-yapsa=1.12.0
  - r-quadprog
  - r-cairo
  - r-nnls=1.4
